### ISSUE TITLE
add styling, images, and syntax highlighting

### ISSUE THREAD

**Issue by thescientist13** [thescientist13/from-webpack-to-web-apis#5]
Likeley somewhere in between #2 and #4 , will want to do a round of just making things look nice, picking a theme, syntax highlighting, etc.

1. [x] Prism Syntax highlighting
1. [x] Presentation Theme
1. [x] Add webpack logo to _Why Webpack_ title card
1. [ ] Add a browser logo to _Why Not Webpack_ title card
1. [x] Maybe try this for the font?
    ```css
    * {
      font-family: system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Open Sans', 'Helvetica Neue', sans-serif!important;
    }
    ```
